# spring:
#   data:
#     mongodb:
#       database: LindaDB
#       host: mongo_container
#       port: 27017
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
